# Generated by Django 2.2 on 2019-05-05 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190505_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='access_level',
            field=models.CharField(max_length=30),
        ),
    ]
