# Generated by Django 2.2 on 2019-05-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20190505_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='staff',
            field=models.CharField(choices=[('DEV', 'DEVELOPER'), ('PG', 'PROJECT MANAGER')], default='DEV', max_length=20),
        ),
    ]
