# Generated by Django 2.2 on 2019-05-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_userinfo_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='access_level',
        ),
    ]
