# Generated by Django 2.2 on 2019-05-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20190511_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='startdate',
            field=models.DateField(),
        ),
    ]
