# Generated by Django 2.1.7 on 2019-05-13 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20190511_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='activity_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Closed', 'Closed'), ('InProgress', 'InProgress'), ('Completed', 'Completed'), ('Terminated', 'Terminated'), ('Due', 'Due')], default='Closed', max_length=10)),
                ('person_incharge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.staff')),
            ],
        ),
        migrations.CreateModel(
            name='task_deliverables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='deliverables/')),
                ('related_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.task')),
            ],
        ),
        migrations.RenameField(
            model_name='project',
            old_name='projectname',
            new_name='project_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='startdate',
        ),
        migrations.AddField(
            model_name='task',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.AddField(
            model_name='activity_log',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
